### ISSUE TITLE
Water Effect Needs Improving

### ISSUE THREAD

**Issue by zcanann** [Squalr/Squally#125]
The water wave effect has some issues. This can be seen by going to the docks to the right of the first town.

Relevant files:
`Engine/Physics/Liquid/LiquidNode.cpp`
`Engine/Physics/Liquid/LiquidTop.cpp`
`Source/Objects/Platformer/Liquids/Water.cpp`

Currently, `Water.cpp` is hard coded to make splashes periodically in the `update` method to keep the water active.

Also, these hard coded splashes do not scale well, as there are a constant number of splashes per second. The wave code needs to function identical regardless of the width of the water.

These splashes are too harsh, and look like something is getting dropped in the water, rather than like actual waves. Ideally, the water would look like there are natural waves constantly, without this harsh effect.

**Comment by zcanann** [comment]
![ezgif-2-bb6b46bac7dc](https://user-images.githubusercontent.com/5906208/63317240-dedf4c80-c2c6-11e9-84ce-add76190b6b0.gif)

**Comment by pbmiguel** [comment]
I'll be happy to help

**Comment by zcanann** [comment]
Guess I missed your message, sorry I couldnt be more helpful!

I ended up resolving this with the last release.
