### ISSUE TITLE
error compiling Permission Denied 

### ISSUE THREAD

**Issue by harrcorr** [Squalr/Squally#127]
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Squalr/cocos2d-x.git' into submodule path '(PATH TO SQUALLY FILE) cocos2d' failed
Failed to clone 'cocos2d' a second time, aborting

**Comment by brsh1** [comment]
make sure you updated github with your public ssh key.

**Comment by zcanann** [comment]
Closing, likely this needs to be done: https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

(select your platform from the tabs available)
