### ISSUE TITLE
git fails to download

### ISSUE THREAD

**Issue by stephen45ss** [Squalr/Squally#128]
![2019-08-28_152936](https://user-images.githubusercontent.com/45843593/63890507-c77c1f80-c9a8-11e9-9ab7-a151b6056939.png)
can't download 
![2019-08-28_155531](https://user-images.githubusercontent.com/45843593/63892271-d6fd6780-c9ac-11e9-8f46-bac2e014b586.png)
![2019-08-28_155808](https://user-images.githubusercontent.com/45843593/63892278-d9f85800-c9ac-11e9-92d0-b816e31da65b.png)
Second attempt failed around 64 MB range. Unsure why this is. Shouldn't have anything to do with download speed but I'm assuming that the git server is taking to long to respond so it's timing out possibly?

**Comment by mattbucci** [comment]
closing as this is github related
