### ISSUE TITLE
Broken Puzzle

### ISSUE THREAD

**Issue by AsaAyers** [Squalr/Squally#130]
I'm fairly sure this puzzle is impossible to solve, because I think the left-shift is producing the wrong result. I just got Squally on Steam today, so I have not yet attempted to download and compile it.

![image](https://user-images.githubusercontent.com/324999/71487845-65a2b980-27d2-11ea-8a8e-c47fa46f8d04.png)

**Comment by zcanann** [comment]
Oops! I thought I had fixed this one. Either I didn't actually fix it, or I botched the release

What platform is this on?

**Comment by AsaAyers** [comment]
This was on Windows

**Comment by zcanann** [comment]
Finally fixed this on dev branch -- will be public in the next release
