### ISSUE TITLE
Optimizations break Linux Build

### ISSUE THREAD

**Issue by zcanann** [Squalr/Squally#131]
On the second map with the dart launchers, optimizations appear to break the `DartLauncher::shoot(float dt)` function, resulting in a segfault.

The line `volatile float* dtPtr = &dt` ends up resolving to `nullptr` due to an optimization (so much for volatile?)

It is unclear why this is happening, as the function is prefixed with our `NO_OPTIMIZE` macro, which should properly disable GCC/G++ optimizations.

For now, this means Linux binaries must be compiled in Debug mode when releasing on Steam. Fortunately, I've spent a considerable amount of time recently optimizing performance, so this shouldn't be a huge issue, but Linux users can expect to have frames dropped until this is resolved.

**Comment by zcanann** [comment]
Here is the relevant function:

https://github.com/Squalr/Squally/blob/develop/Source/Objects/Platformer/Traps/DartTraps/DartLauncher/DartLauncher.cpp

```
NO_OPTIMIZE void DartLauncher::shoot(float dt)
{
	if (this->launchTimer <= 0.0f)
	{
		this->launchTimer = RandomHelper::random_real(DartLauncher::LaunchCooldownMin, DartLauncher::LaunchCooldownMax);

		this->dartPool->getNextDart();
	}

	volatile float* timePtr = &this->launchTimer;
	volatile float* dtPtr = &dt;

	ASM(push ZAX);
	ASM(push ZBX);
	ASM_MOV_REG_VAR(ZAX, timePtr);
	ASM_MOV_REG_VAR(ZBX, dtPtr);
	ASM(movss xmm0, [ZAX])
	ASM(movss xmm1, [ZBX])

	HACKABLE_CODE_BEGIN(LOCAL_FUNC_ID_SHOOT);
	ASM(subps xmm0, xmm1);
	ASM(movss [ZAX], xmm0);
	ASM_NOP10();
	HACKABLE_CODE_END();

	ASM(pop ZBX);
	ASM(pop ZAX);

	HACKABLES_STOP_SEARCH();
}
END_NO_OPTIMIZE
```

**Comment by mattbucci** [comment]
NO_OPTIMIZE_MACRO is defined here: https://github.com/Squalr/Squally/blob/ed8f7c5e15dbee692be0a0e383973a51bab868b9/Source/Engine/Hackables/HackableCode.h#L63

```
	#elif __GNUC__
		#define NO_OPTIMIZE \
			_Pragma("GCC push_options") \
			_Pragma("GCC optimize (\"O0\")") \
			 __attribute__((optimize("O0")))
		#define END_NO_OPTIMIZE \
			_Pragma("GCC pop_options")
	#endif
```

**Comment by mattbucci** [comment]
@zcanann can you include the gcc version used for compilation as well? 

There seem to be 2 caveats with this approach, 

- it only can be used to exclude optimization on entire functions, not specific statements (above code seems to meet this requirement)

- the min version supported is GCC 4.4.

**Comment by mattbucci** [comment]
There's also an alternative attribute syntax proposed here if all else fails, but I'd rather keep the macro as is https://stackoverflow.com/a/9044490/1752064

**Comment by zcanann** [comment]
Turns out that this was misdiagnosed partially. Linux optimizations were causing the problem, however it was only 1 very specific case:

```
	volatile float* timePtr = &this->launchTimer;
	volatile float* dtPtr = &dt;
```

Needs to be
```
	static volatile float* timePtr;
	static  volatile float* dtPtr;

	timePtr = &this->launchTimer;
	float* dtPtr = &dt;
```

I'm not sure why, but Linux hates the way I've been prepping floating point values to be loaded into inline assembly. Making local variables static solves this.

I'm considering this solved via this workaround.
