### ISSUE TITLE
World Music Stops after first zone [Windows]

### ISSUE THREAD

**Issue by GH-Rake** [Squalr/Squally#132]
The music in the first zone works fine as well as inside all the mini games, even the scripted mini games during the campaign.  But after the first zone the music in the world zones stops playing.

I am on Windows 10 1903.  If you can confirm this issue please do

**Comment by GH-Rake** [comment]
clarification:  The first zone has the burning ship so you have the ambient fire noise, but in the second zone there is nothing.  I would expect forest.mp3 to play

**Comment by zcanann** [comment]
My dumbass finally got around to this, gonna be fixed when this release goes live
