### ISSUE TITLE
No Such File: 'cereal/cereal.hpp'

### ISSUE THREAD

**Issue by Mezo-hx** [Squalr/Squally#158]
just as the title says, I keep getting the error "No Such File: 'cereal/cereal.hpp'. I think I did everything correctly...

Full Error:

```
Error C1083 Cannot open include file: 'cereal/cereal.hpp': No such file or directory	
C:\Users\Mezo\Documents\Squally\build\798cd737-8571-41b6-9aa7-a954cf4fbaff\x86-Release\Squally	
C:\Users\Mezo\Documents\Squally\cocos2d\cocos\platform\CCFileUtils.cpp	38	
```

**Comment by zcanann** [comment]
Strange, I made this a CMake dependency instead of vcpkg, wonder if it's a cmake version issue

**Comment by Smotto** [comment]
For now can manually install cereal using vcpkg and other libraries that aren't installed by CMake, then run GenerateCMakeFiles.py, GenerateResources.py, and CopyResources.py

**Comment by zcanann** [comment]
Should be resolved on develop branch.

Will be awhile before it makes its way to master
