### ISSUE TITLE
'pop' crashes the game

### ISSUE THREAD

**Issue by stuxxn** [Squalr/Squally#162]
**System info**:

Steam version with "steam play compatibility" turned on --> "Proton experimental"
```bash
➜  .steam uname -a
Linux TurtleHouse 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
➜  .steam cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

```

I used 'pop' for two different scripts and the game crashed.

The first one was a single byte script, which was something like
```asm
dec esi
```
and should be changed to 
```asm
inc esi
```

but using 
```asm
pop esi
```
crashed the game.

Another example script looked like:
```asm
mov dword ptr[esi], -0.5f
```
which I replaced with
```asm
pop esi
mov dword ptr[esi], -0.5f
```

This also resulted in a crash.

Is this an intended behavior ?
Tbh writing garbage in your game hacks also result in a crash :-).

If you need the exact script names let me know.

**Comment by zcanann** [comment]
Intended behavior, you should always try to balance push/pop commands, as these effect the stack.

For every pop, there should be a push before it somewhere.

And the x86 isn't emulated in this game by design, so assembly bugs can easily crash yeah
