### ISSUE TITLE
Bug: Combat Scenes Crash on OSX

### ISSUE THREAD

**Issue by mattbucci** [Squalr/Squally#93]
![screen shot 2019-02-23 at 9 56 14 pm](https://user-images.githubusercontent.com/3284147/53295711-240e4000-37b6-11e9-972b-591738d2b480.jpg)

**Comment by alex-evelyn** [comment]
I also get the crash, but it happens after I beat the enemy (I am in intro level, just beat enemy 2). This crash causes my mac to lock the screen after it displays random pixels all over the screen.
I just downloaded the game 10 minutes ago from Steam.
