### ISSUE TITLE
Bug: Double Cursor on OSX

### ISSUE THREAD

**Issue by mattbucci** [Squalr/Squally#94]
bug is probably somewhere in GLFW, waiting for https://github.com/glfw/glfw/issues/1098 as the section of code controlling this cursor hide feature has been rewritten

**Comment by mattbucci** [comment]
Not sure if this is still happening, but much newer versions are now available:
https://github.com/microsoft/vcpkg/blob/master/ports/glfw3/portfile.cmake

**Comment by zcanann** [comment]
glfw should be upgraded, going to close until any users encounter it again
